- name: "security"
  color: "d73a4a"
  description: "Security-related changes"
- name: "dependencies"
  color: "0366d6"
  description: "Updates to dependencies"
- name: "auto-merge"
  color: "28a745"
  description: "PRs that can be automatically merged"